// <auto-generated />
namespace ddac.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update61 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update61));
        
        string IMigrationMetadata.Id
        {
            get { return "201801210745489_update61"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
